# Hyper parameter experiment - varied KME, E and K

In this experiment three variables were varied:
- KME
- E
- K

As the results demonstrate, the best scores where achieved with a KME that embeds all four variables at the same time (4) or one that embeds the two pairs that are being tested on t-separation. The KME that uses marginal distributions does not work.

Interesting to see is that the linearly generated data with 0 randomness is harder to classify than the data with 005 randomness. This corresponds to what Scholkopf says about the zero mean Gaussian case being what is most difficult to crack (I am however not sure how this exactly corresponds, but I presume it is related).

In [37]:
import pandas as pd
import numpy as np
import itertools

In [6]:
results_0 = pd.read_csv('0_results.csv')
# Missing values here.
#results_001 = pd.read_csv('001_results.csv')
results_005 = pd.read_csv('005_results.csv')
results_ran_001 = pd.read_csv('001_ran_results.csv')
results_ran_005 = pd.read_csv('005_ran_results.csv')

In [35]:
for i in [results_0, results_005, results_ran_001, results_ran_005]:
    df = i
    df['var_score'] = np.sqrt(df['var_score'])
    print(df[df['KME'] == '4'].describe()[['best_score','mean_score','var_score']])

       best_score  mean_score  var_score
count    9.000000    9.000000   9.000000
mean     0.774972   73.297419   1.458214
std      0.010865    0.803000   0.045760
min      0.761616   72.646465   1.390177
25%      0.765657   72.747475   1.425732
50%      0.771717   72.888889   1.457755
75%      0.783838   73.959596   1.501703
max      0.791919   74.888889   1.513861
       best_score  mean_score  var_score
count    9.000000    9.000000   9.000000
mean     0.854097   82.038159   1.355914
std      0.007162    0.521005   0.080187
min      0.842424   81.353535   1.230369
25%      0.848485   81.656566   1.312727
50%      0.855556   82.202020   1.361719
75%      0.857576   82.323232   1.423483
max      0.865657   82.949495   1.471736
       best_score  mean_score  var_score
count    9.000000    9.000000   9.000000
mean     0.748934   72.453423   1.187686
std      0.006702    0.752855   0.082720
min      0.737374   71.434343   1.086977
25%      0.743434   71.757576   1.128062
50%      0.751515   72.666667   1.179717
75%      0.754545   73.030303   1.244186
max      0.755556   73.595960   1.318227
       best_score  mean_score  var_score
count    9.000000    9.000000   9.000000
mean     0.778676   73.261504   1.522527
std      0.018255    1.350559   0.026233
min      0.758586   71.717172   1.480563
25%      0.760606   72.121212   1.511206
50%      0.773737   72.929293   1.512879
75%      0.791919   74.727273   1.534739
max      0.808081   75.090909   1.559324

In [46]:
E_list = [500,1000,1500]
K_list = [200,400,800]
total = pd.concat([results_0, results_005, results_ran_001, results_ran_005])
total['var_score'] = np.sqrt(total['var_score'])
for prod in itertools.product(E_list,K_list):
    E, K = prod
    print(prod)
    print(total[(total['E'] == E) & (total['K'] == K)].describe()[['best_score','mean_score','var_score']])

(500, 200)
       best_score  mean_score  var_score
count   13.000000   13.000000  13.000000
mean     0.665035   62.523699   1.022237
std      0.172872   15.537434   0.030233
min      0.413131   40.727273   0.967335
25%      0.433333   41.333333   1.001034
50%      0.749495   67.919192   1.013421
75%      0.774747   72.121212   1.052969
max      0.848485   81.656566   1.062868
(500, 400)
       best_score  mean_score  var_score
count   13.000000   13.000000  13.000000
mean     0.667288   63.275835   1.012938
std      0.181926   16.184916   0.034931
min      0.409091   40.525253   0.949265
25%      0.413131   40.828283   0.998780
50%      0.760606   70.848485   1.013185
75%      0.774747   73.959596   1.037816
max      0.860606   82.262626   1.057102
(500, 800)
       best_score  mean_score  var_score
count   13.000000   13.000000  13.000000
mean     0.672494   63.117327   0.943445
std      0.184726   15.973014   0.285448
min      0.406061   40.606061   0.000000
25%      0.421212   40.929293   0.987459
50%      0.756566   70.262626   1.014979
75%      0.785859   72.787879   1.045306
max      0.855556   81.515152   1.076805
(1000, 200)
       best_score  mean_score  var_score
count   13.000000   13.000000  13.000000
mean     0.673271   62.834499   1.023297
std      0.178555   15.695419   0.028043
min      0.412121   40.868687   0.983458
25%      0.428283   41.111111   0.999347
50%      0.758586   69.777778   1.014684
75%      0.787879   71.959596   1.054737
max      0.850505   82.202020   1.067217
(1000, 400)
       best_score  mean_score  var_score
count   13.000000   13.000000  13.000000
mean     0.665035   63.392385   1.013331
std      0.179559   16.320174   0.032272
min      0.410101   40.343434   0.961032
25%      0.413131   40.727273   0.999148
50%      0.749495   71.717172   1.012365
75%      0.772727   74.060606   1.037862
max      0.856566   82.323232   1.058351
(1000, 800)
       best_score  mean_score  var_score
count   13.000000   13.000000  13.000000
mean     0.676535   63.351981   1.010759
std      0.189181   16.203518   0.047673
min      0.406061   40.585859   0.907747
25%      0.413131   40.686869   0.978571
50%      0.765657   70.989899   1.015177
75%      0.798990   73.070707   1.045566
max      0.864646   81.656566   1.076771
(1500, 200)
       best_score  mean_score  var_score
count   13.000000   13.000000  13.000000
mean     0.668687   62.705517   1.019897
std      0.179533   15.798816   0.031847
min      0.410101   40.646465   0.963708
25%      0.421212   40.909091   0.989784
50%      0.759596   68.646465   1.013286
75%      0.783838   72.202020   1.054344
max      0.848485   82.424242   1.066474
(1500, 400)
       best_score  mean_score  var_score
count   13.000000   13.000000  13.000000
mean     0.668376   63.773116   1.010992
std      0.183305   16.615311   0.036336
min      0.406061   40.424242   0.953648
25%      0.412121   40.686869   0.998162
50%      0.754545   71.939394   1.013668
75%      0.783838   74.727273   1.039299
max      0.865657   82.949495   1.057005
(1500, 800)
       best_score  mean_score  var_score
count   13.000000   13.000000  13.000000
mean     0.675602   63.255633   1.014910
std      0.187563   16.117743   0.039213
min      0.407071   40.626263   0.953961
25%      0.414141   40.727273   0.976787
50%      0.763636   70.949495   1.013089
75%      0.794949   73.010101   1.049491
max      0.860606   81.353535   1.076488

In [47]:
results_0

         KME     E    K  best_score  mean_score  var_score
0    minimal   500  200    0.749495   67.919192   1.023926
1    minimal   500  400    0.763636   70.848485   1.026544
2    minimal   500  800    0.759596   70.262626   1.030183
3    minimal  1000  200    0.787879   69.777778   1.029585
4    minimal  1000  400    0.766667   72.040404   1.028643
5    minimal  1000  800    0.772727   70.989899   1.031470
6    minimal  1500  200    0.759596   68.646465   1.026749
7    minimal  1500  400    0.761616   71.939394   1.027522
8    minimal  1500  800    0.772727   70.949495   1.032397
9          4   500  200    0.778788   72.646465   1.025933
10         4   500  400    0.770707   73.959596   1.022583
11         4   500  800    0.761616   72.888889   1.022415
12         4  1000  200    0.786869   72.767677   1.025738
13         4  1000  400    0.771717   74.060606   1.023836
14         4  1000  800    0.765657   72.747475   1.020803
15         4  1500  200    0.791919   72.707071   1.026255
16         4  1500  400    0.783838   74.888889   1.025100
17         4  1500  800    0.763636   73.010101   1.021803
18  marginal   500  200    0.433333   41.333333   1.002069
19  marginal   500  400    0.413131   40.525253   0.997561
20  marginal   500  800    0.408081   40.606061   0.970052
21  marginal  1000  200    0.412121   40.868687   0.979371
22  marginal  1000  400    0.411111   40.343434   0.998297
23  marginal  1000  800    0.406061   40.585859   0.952758
24  marginal  1500  200    0.410101   40.666667   0.979371
25  marginal  1500  400    0.412121   40.424242   0.996328
26  marginal  1500  800    0.407071   40.626263   0.952758
27     extra   500  200    0.774747   72.060606   1.027023
28     extra   500  400    0.774747   70.848485   1.026442
29     extra   500  800    0.756566   71.838384   1.024653
30     extra  1000  200    0.768687   71.959596   1.026160
31     extra  1000  400    0.772727   71.717172   1.024883
32     extra  1000  800    0.798990   73.636364   1.027659
33     extra  1500  200    0.773737   72.202020   1.026411
34     extra  1500  400    0.768687   73.050505   1.024603
35     extra  1500  800    0.794949   73.474747   1.026348